package net.dahanne.showcase.enums;

public enum ErrorTypes {
  USER_ALREADY_EXISTS,
  USER_NOT_FOUND,
  ACCOUNT_NOT_FOUND,
  MAX_USERS_REACHED,
  UNAUTHORIZED,
  OPERATION_CANCELLED,
  CONFIGURATION_ERROR,
  INVALID_RESPONSE,
  TRANSPORT_ERROR,
  UNKNOWN_ERROR;
}
